services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./__data/mysql/:/var/lib/mysql/ # ./__data/mysql/ 路径可以替换成自己的路径
      - ./deploy/sql/:/docker-entrypoint-initdb.d/ # 初始化的脚本，若 ./__data/mysql/ 文件夹存在数据，则不会执行初始化脚本
    env_file:
      - .env
      - .env.development
    ports:
      - "${DB_PORT:-3304}:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置utf8字符集

    networks:
      - nest_admin_net

  app:
    build: ./
    container_name: admin-server
    restart: always
    command: [ "pm2-runtime", "ecosystem.config.js" ]
    env_file:
      - .env
      - .env.development
    ports:
      - "${APP_PORT:-3000}:3000"
    networks:
      - nest_admin_net

networks:
  nest_admin_net:
    driver: bridge


#要看效果到这层级 输入 docker compose config
